In [1]:
import numpy as np

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [21]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.randint(1,60,(4,4))

array([[16, 58, 24, 26],
       [23, 27, 28, 34],
       [30, 25, 54, 15],
       [19, 58, 54,  9]])

In [27]:
arr=np.random.randint(0,50,10)

In [29]:
arr

array([24, 35, 10,  6, 47, 31,  5, 11,  3, 17])

In [33]:
np.reshape(arr,(2,5))

array([[24, 35, 10,  6, 47],
       [31,  5, 11,  3, 17]])

In [35]:
arr.max()

47

In [37]:
arr.argmax()

4

In [41]:
arr.shape

(10,)

In [43]:
arr=np.reshape(arr,(2,5))

In [45]:
arr.shape

(2, 5)

In [47]:
a=np.arange(0,11)

In [49]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
b=a[:5]

In [53]:
b

array([0, 1, 2, 3, 4])

In [55]:
c=b.copy()

In [57]:
c

array([0, 1, 2, 3, 4])

In [59]:
c[:3]=5

In [61]:
c

array([5, 5, 5, 3, 4])

In [63]:
b

array([0, 1, 2, 3, 4])

In [65]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
b[:3]=5

In [69]:
b

array([5, 5, 5, 3, 4])

In [71]:
a

array([ 5,  5,  5,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
a=np.arange(0,15)

In [127]:
np.array(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [129]:
a.shape

(15,)

In [131]:
b=np.reshape(a,(3,5))

In [135]:
b.shape

(3, 5)

In [137]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [151]:
b[:2,1:3]

array([[1, 2],
       [6, 7]])

In [157]:
a=np.arange(1,11)

In [159]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [161]:
boo=a>3

In [163]:
boo

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [171]:
a[boo==False]

array([1, 2, 3])